// Code generated by Kitex v0.0.4. DO NOT EDIT.
package demoservice

import (
	"github.com/cloudwego/kitex/server"
	"github.com/wuwentao1998/golang-demos/kitex-server/kitex_gen/demo"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler demo.DemoService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
