// Code generated by Kitex v0.0.4. DO NOT EDIT.

package demo

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/wuwentao1998/golang-demos/kitex-server/kitex_gen/demo"
)

func serviceInfo() *kitex.ServiceInfo {
	return demoServiceInfo
}

var demoServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "Demo"
	handlerType := (*demo.Demo)(nil)
	methods := map[string]kitex.MethodInfo{
		"echo": kitex.NewMethodInfo(echoHandler, newDemoEchoArgs, newDemoEchoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "demo",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.0.4",
		Extra:           extra,
	}
	return svcInfo
}

func echoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*demo.DemoEchoArgs)
	realResult := result.(*demo.DemoEchoResult)
	success, err := handler.(demo.Demo).Echo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDemoEchoArgs() interface{} {
	return demo.NewDemoEchoArgs()
}

func newDemoEchoResult() interface{} {
	return demo.NewDemoEchoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Echo(ctx context.Context, req *demo.Request) (r *demo.Response, err error) {
	var _args demo.DemoEchoArgs
	_args.Req = req
	var _result demo.DemoEchoResult
	if err = p.c.Call(ctx, "echo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
